version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.9-stretch

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
